version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/ShoppersShop/coinflip
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make deps
      - run:
          name: Compile
          command: make build
